# Generated by Django 5.0.4 on 2024-05-20 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('price', models.BigIntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('slug', models.TextField(unique=True)),
                ('buyer_name', models.CharField(max_length=20)),
                ('buyer_phone', models.CharField(max_length=15)),
                ('buyer_address', models.CharField(max_length=200)),
                ('ongkir', models.BigIntegerField(default=0)),
                ('sale_date', models.DateField()),
                ('created_at', models.DateTimeField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('price', models.BigIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kasir.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kasir.sale')),
            ],
        ),
    ]
